---
title: 异常类
toc: true
date: 2020-07-18 10:46:47
categories:
 - Java
 - Java面向对象
---
<meta name="referrer" content="no-referrer"/>

## 一、异常的作用域
下面的程序执行会失败，这是因为 `int len` 这个变量是定义在 try 的代码块里，所以如果想要操作 len 这个变量，那么就需要我们提升作用域。
```java
        try {
            int len = getStrLength(null);
        } catch (NullPointerException e) {
        }

        System.out.println("程序执行到这"+len);
```
## 二、异常的分类
异常分为 `RuntimeException`  和其余的 `Exception` ，两者的<font color=red>**不同点**</font>：<br />1、<br />手工抛出 `RuntimeException` 异常时，<font color=red>**不需要在方法上约定可能抛出的异常**</font>。类似 `IllegalArgumentException` 是 `RuntimeException` 子类抛出异常时就不需要在方法上声明。
```java
public static int getInt(String str){
    if(str == null){
        throw new IllegalArgumentException("姓名不能为空");
    }
    return Integer.parseInt(str);
}
```
手工抛出其余的 `Exception` 异常时，<font color=red>**必须在方法上约定可能抛出的异常**</font>。类似如下代码
```java
 public static int getInt(String str) throws Exception{
        if(str == null){
            throw new Exception("姓名不能为空");
        }
        return Integer.parseInt(str);
    }
```
2、<br />`Exception` ：受检查的异常，这种异常是<font color=red>**强制我们catch或throw的异常**</font>。你遇到这种异常必须进行catch或throw，如果不处理，编译器会报错。比如：IOException。<br />`RuntimeException` ：运行时异常，<font color=red>**这种异常我们不需要处理，完全由虚拟机接管**</font>。比如我们常见的NullPointerException，我们在写程序时不会进行catch或throw。